#功能:
#>计分板改变(提示:使用此功能后,服务器内不能有其它插件的功能是改变计分板的,否则会产生冲突)
#  >玩家前缀
#  >玩家后缀
#  >侧边栏显示信息
#################################
#####       语言文件        #####
#################################
#可以使用相对路径(是相对于服务端所在文件夹的路径)
language: "plugins/Lib_msg/language_cn.yml"
#################################
#####         描述          #####
#################################
description:
  - "&7- 重新读取config.yml"
  - "&7- 重新读取language.yml"
#################################
#####         配置          #####
#################################
per: "lib.msg"                #类型管理权限

side:
  size: 5                       #行数,0-16(修改后必须重启服务器生效)