#功能:
#>计分板改变(提示:使用此功能后,服务器内不能有其它插件的功能是改变计分板的,否则会产生冲突)
#  >玩家前后缀
#  >侧边栏显示信息
#################################
#####       语言文件        #####
#################################
lang:
  default: "cn"                #默认语言(指不明确指定语言的情况下)
  error: "en"                  #错误时使用语言(指指定的语言配置不存在时使用的语言配置)
#################################
#####         描述          #####
#################################
description:
  - "&7- 重新读取config.yml"
  - "&7- 重新读取language.yml"
#################################
#####         配置          #####
#################################
per: "lib.msg.admin"          #管理权限

#前缀配置
prefix:
  per: "lib.msg.prefix"      #选择前缀需要的权限
  auto: true                   #是否自动选择
#后缀配置
suffix:
  per: "lib.msg.suffix"
  auto: true

side:
  size: 5                       #行数,0-16(修改后必须重启服务器生效)
  #格式'行号 获取器名[ 数据]'
  #行号:
  #  -1: 标题
  #  >=0: 表示行,0在最下面
  #数据: 可含空格
  sides:
    - "-1 info &b[E世界]&a{name}"
    - "4 info &eQQ群306825355"
    - "3 gold"
    - "2 world"
    - "1 dir"
    - "0 speed"